version: '3'
services:
  cassandra:
    image: cassandra:3.0.13
    environment:
       MAX_HEAP_SIZE: 1G
       HEAP_NEWSIZE: 800M
  migrate:
    build: .
    environment:
      CASSANDRA_HOST: cassandra
